# Generated by Django 5.2.7 on 2025-11-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donor', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donoralertresponse',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.donorprofile'),
        ),
    ]
